# Generated by Django 5.0 on 2024-01-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=30)),
                ('book_price', models.IntegerField()),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
