# Generated by Django 5.0 on 2024-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('sal', models.FloatField()),
                ('job', models.CharField(max_length=20)),
                ('deptno', models.IntegerField()),
            ],
        ),
    ]
